<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>cn.herodotus.ecosystem</groupId>
        <artifactId>herodotus-ecosystem-parent</artifactId>
        <version>4.1.0.2</version>
        <relativePath/>
    </parent>

    <groupId>cn.herodotus.thingsbrain</groupId>
    <artifactId>thingsbrain</artifactId>
    <name>${project.artifactId}</name>

    <packaging>pom</packaging>

    <description>Dante Cloud 生态产品 -- ThingsBrain 物联网平台</description>

    <url>https://github.com/dante-compass/thingsbrain</url>

    <licenses>
        <license>
            <name>Apache License Version 2.0</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <scm>
        <url>https://github.com/dante-compass/thingsbrain</url>
        <connection>scm:git:git@github.com:dante-compass/thingsbrain.git</connection>
        <developerConnection>scm:git:git@github.com:dante-compass/thingsbrain.git</developerConnection>
    </scm>

    <organization>
        <name>dromara</name>
        <url>https://dromara.org</url>
    </organization>

    <developers>
        <developer>
            <id>herodotus-ecosystem</id>
            <name>码匠君</name>
            <email>herodotus@aliyun.com</email>
            <organization>dromara</organization>
            <organizationUrl>https://dromara.org</organizationUrl>
            <url>https://github.com/herodotus-ecosystem</url>
        </developer>
    </developers>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>cn.herodotus.dante</groupId>
                <artifactId>dante-dependencies</artifactId>
                <version>${project.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>cn.herodotus.dantecloud</groupId>
                <artifactId>dante-cloud-dependencies</artifactId>
                <version>${project.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>cn.herodotus.thingsbrain</groupId>
                <artifactId>thingsbrain-dependencies</artifactId>
                <version>${project.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <profiles>
        <!-- 覆盖 herodotus-ecosystem-parent 中的 release 和 github action profile 实现非服务模块的发布-->
        <!-- 非服务模块代码不涉及动态配置信息，所以不需要有像前面一样的配置信息-->
        <profile>
            <id>release</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-source-plugin</artifactId>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-javadoc-plugin</artifactId>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-gpg-plugin</artifactId>
                    </plugin>
                    <plugin>
                        <groupId>org.sonatype.central</groupId>
                        <artifactId>central-publishing-maven-plugin</artifactId>
                        <configuration>
                            <excludeArtifacts>
                                <excludeArtifact>thingsbrain-herodotus-cloud-ability</excludeArtifact>
                                <excludeArtifact>thingsbrain-monolith-application</excludeArtifact>
                            </excludeArtifacts>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <profile>
            <id>githubAction</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-source-plugin</artifactId>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-javadoc-plugin</artifactId>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-gpg-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>sign-artifacts</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>sign</goal>
                                </goals>
                                <configuration>
                                    <!-- 必须配置，用于 gpg 非交互式密码输入 -->
                                    <gpgArguments>
                                        <arg>--pinentry-mode</arg>
                                        <arg>loopback</arg>
                                    </gpgArguments>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.sonatype.central</groupId>
                        <artifactId>central-publishing-maven-plugin</artifactId>
                        <configuration>
                            <excludeArtifacts>
                                <excludeArtifact>thingsbrain-herodotus-cloud-ability</excludeArtifact>
                                <excludeArtifact>thingsbrain-monolith-application</excludeArtifact>
                            </excludeArtifacts>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

    <modules>
        <module>thingsbrain-dependencies</module>
        <module>thingsbrain-kernel</module>
        <module>thingsbrain-link</module>
        <module>thingsbrain-mqtt</module>
        <module>thingsbrain-persistence</module>
        <module>thingsbrain-platform</module>
        <module>thingsbrain-nosql</module>
    </modules>

</project>