<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.dromara.thingsbrain</groupId>
        <artifactId>thingsbrain</artifactId>
        <version>4.0.6.5</version>
    </parent>

    <artifactId>thingsbrain-kernel</artifactId>
    <name>${project.artifactId}</name>

    <packaging>pom</packaging>

    <description>ThingsBrain 物联网平台核心定义相关模块分组</description>

    <modules>
        <module>thingsbrain-kernel-commons</module>
        <module>thingsbrain-kernel-link</module>
        <module>thingsbrain-kernel-tsl</module>
    </modules>

</project>