<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.dromara.thingsbrain</groupId>
        <artifactId>thingsbrain-infrastructure</artifactId>
        <version>4.0.5.2</version>
    </parent>

    <artifactId>thingsbrain-infrastructure-autoconfigure</artifactId>
    <name>${project.artifactId}</name>

    <description>ThingsBrain 物联网平台基础设施自动配置模块</description>

    <dependencies>
        <dependency>
            <groupId>org.dromara.thingsbrain</groupId>
            <artifactId>thingsbrain-infrastructure-tsdb</artifactId>
        </dependency>

        <dependency>
            <groupId>org.dromara.thingsbrain</groupId>
            <artifactId>thingsbrain-infrastructure-mqtt</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.integration</groupId>
            <artifactId>spring-integration-mqtt</artifactId>
            <optional>true</optional>
            <exclusions>
                <exclusion>
                    <artifactId>org.eclipse.paho.client.mqttv3</artifactId>
                    <groupId>org.eclipse.paho</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.eclipse.paho</groupId>
            <artifactId>org.eclipse.paho.mqttv5.client</artifactId>
            <optional>true</optional>
        </dependency>
    </dependencies>

</project>