<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>cn.herodotus.thingsbrain</groupId>
        <artifactId>thingsbrain-platform</artifactId>
        <version>4.1.0.0</version>
    </parent>

    <artifactId>thingsbrain-platform-autoconfigure</artifactId>
    <name>${project.artifactId}</name>

    <description>ThingsBrain 物联网平台平台功能自动配置模块</description>

    <dependencies>

        <dependency>
            <groupId>cn.herodotus.thingsbrain</groupId>
            <artifactId>thingsbrain-platform-rest</artifactId>
        </dependency>

        <dependency>
            <groupId>cn.herodotus.thingsbrain</groupId>
            <artifactId>thingsbrain-platform-authentication</artifactId>
        </dependency>

        <dependency>
            <groupId>cn.herodotus.thingsbrain</groupId>
            <artifactId>thingsbrain-mqtt-autoconfigure</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-restclient</artifactId>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>cn.herodotus.thingsbrain</groupId>
            <artifactId>thingsbrain-link-autoconfigure</artifactId>
        </dependency>

    </dependencies>

</project>