<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.dromara.thingsbrain</groupId>
        <artifactId>thingsbrain-link</artifactId>
        <version>4.0.6.0</version>
    </parent>

    <artifactId>thingsbrain-link-commons</artifactId>
    <name>${project.artifactId}</name>

    <description>ThingsBrain 物联网平台自定义 Link 协议通用代码模块</description>

    <dependencies>

        <dependency>
            <groupId>org.dromara.thingsbrain</groupId>
            <artifactId>thingsbrain-persistence-commons</artifactId>
        </dependency>

        <dependency>
            <groupId>org.dromara.thingsbrain</groupId>
            <artifactId>thingsbrain-kernel-link</artifactId>
        </dependency>
    </dependencies>
</project>