<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>cn.herodotus.thingsbrain</groupId>
        <artifactId>thingsbrain</artifactId>
        <version>4.1.0.3</version>
    </parent>

    <artifactId>thingsbrain-nosql</artifactId>
    <name>${project.artifactId}</name>

    <packaging>pom</packaging>

    <description>ThingsBrain 物联网平台 NoSQL 非结构化数据存储相关模块分组</description>

    <modules>
        <module>thingsbrain-nosql-influxdb3</module>
        <module>thingsbrain-nosql-autoconfigure</module>
    </modules>

</project>