/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright (c) 2020-2030 郑庚伟 ZHENGGENGWEI (码匠君), <herodotus@aliyun.com> Licensed under the AGPL License
 *
 * This file is part of Herodotus ThingsBrain.
 *
 * Herodotus ThingsBrain is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Herodotus ThingsBrain is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.herodotus.vip>.
 */

-- ----------------------------
-- Table data for iot_product_category
-- ----------------------------
INSERT INTO "iot_product_category" ("category_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "category_name", "scene_id") VALUES ('2bfa5467-b9f5-46dd-acec-f05aaaa00522', '2025-04-24 16:16:11.724', '2025-04-24 16:17:04.647', 'system', 0, 'system', '物联网平台测试数据', 1, 't', 0, '测试品类', NULL);

-- ----------------------------
-- Table data for iot_product
-- ----------------------------
INSERT INTO "iot_product" ("product_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "authentication", "protocol", "networking", "node", "photo_url", "product_key", "product_name", "productsecret", "quantity", "registration", "is_release", "verification", "category_id") VALUES ('8452271e-e42e-4a59-af80-3ea3c83247ea', '2025-04-28 21:20:27.432', '2025-04-28 21:20:27.432', 'system', 0, 'system', NULL, 1, 't', 0, NULL, NULL, 2, 0, NULL, 'apktestadd', '测试物联网产品', '9f3026f4beddf8d29f3026f4beddf8d2', 0, 'f', 'f', 'f', NULL);

-- ----------------------------
-- Table data for iot_mqtt_account
-- ----------------------------
INSERT INTO "iot_mqtt_account" ("account_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "client_id", "password", "username") VALUES ('herodotus-iot-platform', '2025-10-07 22:42:29', '2025-10-07 22:42:32', 'system', 0, 'system', '物联网平台链接Mqtt默认账号', 0, 't', 0, 'herodotus-iot-platform', '{bcrypt}$2a$10$/XF002c2EuL0NyaEZ8a0be8S2IxKjFDd8f1ryY6wHpRMuXCiF2x7K', 'herodotus');

-- ----------------------------
-- Table data for iot_mqtt_account_category
-- ----------------------------
INSERT INTO "iot_mqtt_category" ("category_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "category_name", "is_standard", "action", "area") VALUES ('1', '2025-10-07 22:44:22', '2025-10-07 22:44:24', 'system', 0, 'system', 'ThingsBrain平台端订阅主题分类', 0, 't', 0, 'ThingsBrain平台端订阅主题分类', 'f', 'subscribe', 'PLATFORM');
INSERT INTO "iot_mqtt_category" ("category_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "category_name", "is_standard", "action", "area") VALUES ('2', '2025-10-07 22:45:42', '2025-10-07 22:45:44', 'system', 0, 'system', 'ThingsBrain平台端发布主题分类', 0, 't', 0, 'ThingsBrain平台端发布主题分类', 't', 'publish', 'PLATFORM');
INSERT INTO "iot_mqtt_category" ("category_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "category_name", "is_standard", "action", "area") VALUES ('4', '2025-10-07 22:45:42', '2025-10-07 22:45:44', 'system', 0, 'system', '物联网设备端订阅主题分类', 0, 't', 0, '物联网设备端订阅主题分类', 't', 'subscribe', 'DEVICE');
INSERT INTO "iot_mqtt_category" ("category_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "category_name", "is_standard", "action", "area") VALUES ('3', '2025-10-07 22:45:42', '2025-10-07 22:45:44', 'system', 0, 'system', '物联网设备端发布主题分类', 0, 't', 0, '物联网设备端发布主题分类', 't', 'publish', 'DEVICE');

-- ----------------------------
-- Table data for iot_mqtt_authority
-- ----------------------------
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('1', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/sub/register');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('2', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/topo/add');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('3', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/topo/delete');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('4', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/topo/get');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('5', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/list/found');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('6', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/topo/add/notify_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('7', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'ext/session/+/+/combine/login');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('8', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'ext/session/+/+/combine/batch_login');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('9', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'ext/session/+/+/combine/logout');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('10', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'ext/session/+/+/combine/batch_logout');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('11', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/event/property/post');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('12', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/service/property/set_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('13', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/event/+/post');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('14', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/service/+');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('15', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/event/property/pack/post');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('16', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/event/property/history/post');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('17', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/event/property/batch/post');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('18', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/property/desired/get');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('19', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/property/desired/delete');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('20', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/disable_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('21', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/enable_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('22', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/delete_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('23', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/deviceinfo/update');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('24', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/deviceinfo/get');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('25', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/deviceinfo/delete');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('26', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'ota/device/inform/+/+');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('27', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'ota/device/progress/+/+');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('28', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/ota/firmware/get');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('29', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/file/download');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('30', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/config/get');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('31', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/config/push_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('32', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/config/log/get');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('33', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/log/post');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('34', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/_thing/diag/post');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('35', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'shadow/update/+/+');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('36', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/bootstrap/notify_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('37', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/job/get');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('38', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/job/update');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('39', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/file/upload/mqtt/init');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('40', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/secure_tunnel/proxy/request');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('41', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/sub/register_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('42', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/topo/add_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('43', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/topo/delete_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('44', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/topo/get_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('45', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/list/found_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('46', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/topo/add/notify');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('47', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/topo/change');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('48', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'ext/session/+/+/combine/login_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('49', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'ext/session/+/+/combine/batch_login_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('50', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'ext/session/+/+/combine/logout_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('51', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'ext/session/+/+/combine/batch_logout_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('52', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/event/property/post_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('53', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/service/property/set');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('54', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/event/+/post_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('55', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/service/+');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('56', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/event/property/pack/post_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('57', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/event/property/history/post_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('58', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/event/property/batch/post_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('59', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/property/desired/get_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('60', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/property/desired/delete_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('61', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/disable');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('62', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/enable');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('63', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/delete');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('64', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/deviceinfo/update_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('65', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/deviceinfo/get_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('66', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/deviceinfo/delete_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('67', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'ota/device/upgrade/+/+');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('68', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/ota/firmware/get_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('69', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/file/download_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('70', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/config/get_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('71', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/config/push');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('72', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/config/log/get_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('73', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/config/log/push');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('74', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/log/post_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('75', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/_thing/diag/post_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('76', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'shadow/get/+/+');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('77', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/bootstrap/notify');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('78', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/job/notify');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('79', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/job/get_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('80', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/job/update_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('81', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/file/upload/mqtt/init_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('82', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/secure_tunnel/proxy/request_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('83', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/sub/register_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('84', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/topo/add_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('85', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/topo/delete_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('86', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/topo/get_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('87', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/list/found_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('88', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/topo/add/notify');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('89', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/topo/change');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('90', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'ext/session/+/+/combine/login_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('91', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'ext/session/+/+/combine/batch_login_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('92', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'ext/session/+/+/combine/logout_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('93', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'ext/session/+/+/combine/batch_logout_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('94', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/event/property/post_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('95', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/service/property/set');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('96', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/event/+/post_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('97', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/service/+');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('98', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/event/property/pack/post_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('99', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/event/property/history/post_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('100', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/event/property/batch/post_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('101', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/property/desired/get_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('102', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/property/desired/delete_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('103', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/disable');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('104', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/enable');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('105', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/delete');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('106', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/deviceinfo/update_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('107', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/deviceinfo/get_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('108', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/deviceinfo/delete_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('109', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'ota/device/upgrade/+/+');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('110', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/ota/firmware/get_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('111', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/file/download_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('112', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/config/get_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('113', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/config/push');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('114', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/config/log/get_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('115', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/config/log/push');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('116', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/log/post_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('117', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/_thing/diag/post_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('118', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'shadow/get/+/+');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('119', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/bootstrap/notify');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('120', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/job/notify');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('121', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/job/get_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('122', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/job/update_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('123', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/thing/file/upload/mqtt/init_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('124', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'subscribe', 'allow', 1, 0, 'sys/+/+/secure_tunnel/proxy/request_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('125', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/sub/register');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('126', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/topo/add');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('127', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/topo/delete');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('128', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/topo/get');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('129', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/list/found');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('130', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/topo/add/notify_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('131', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'ext/session/+/+/combine/login');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('132', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'ext/session/+/+/combine/batch_login');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('133', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'ext/session/+/+/combine/logout');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('134', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'ext/session/+/+/combine/batch_logout');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('135', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/event/property/post');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('136', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/service/property/set_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('137', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/event/+/post');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('138', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/service/+');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('139', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/event/property/pack/post');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('140', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/event/property/history/post');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('141', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/event/property/batch/post');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('142', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/property/desired/get');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('143', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/property/desired/delete');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('144', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/disable_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('145', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/enable_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('146', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/delete_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('147', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/deviceinfo/update');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('148', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/deviceinfo/get');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('149', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/deviceinfo/delete');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('150', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'ota/device/inform/+/+');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('151', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'ota/device/progress/+/+');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('152', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/ota/firmware/get');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('153', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/file/download');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('154', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/config/get');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('155', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/config/push_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('156', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/config/log/get');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('157', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/log/post');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('158', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/_thing/diag/post');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('159', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'shadow/update/+/+');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('160', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/bootstrap/notify_reply');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('161', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/job/get');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('162', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/job/update');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('163', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/thing/file/upload/mqtt/init');
INSERT INTO "iot_mqtt_authority" ("authority_id", "create_time", "update_time", "create_by", "reversion", "update_by", "description", "ranking", "is_reserved", "status", "action", "permission", "qos", "retain", "topic") VALUES ('164', '2025-10-13 15:22:00', '2025-10-13 15:22:03', 'system', 0, 'system', NULL, 0, 't', 0, 'publish', 'allow', 1, 0, 'sys/+/+/secure_tunnel/proxy/request');

-- ----------------------------
-- Table data for iot_mqtt_category
-- ----------------------------
INSERT INTO "iot_mqtt_account_category" ("account_id", "category_id") VALUES ('herodotus-iot-platform', '1');
INSERT INTO "iot_mqtt_account_category" ("account_id", "category_id") VALUES ('herodotus-iot-platform', '2');
INSERT INTO "iot_mqtt_account_category" ("account_id", "category_id") VALUES ('83a59414-04b9-4e83-af8a-a756a2e8f01f', '4');
INSERT INTO "iot_mqtt_account_category" ("account_id", "category_id") VALUES ('83a59414-04b9-4e83-af8a-a756a2e8f01f', '3');

-- ----------------------------
-- Table data for iot_mqtt_category_authority
-- ----------------------------
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('1', '1');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('1', '2');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('1', '3');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('1', '4');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('1', '5');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('1', '6');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('1', '7');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('1', '8');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('1', '9');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('1', '10');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('1', '11');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('1', '12');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('1', '13');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('1', '14');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('1', '15');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('1', '16');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('1', '17');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('1', '18');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('1', '19');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('1', '20');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('1', '21');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('1', '22');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('1', '23');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('1', '24');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('1', '25');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('1', '26');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('1', '27');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('1', '28');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('1', '29');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('1', '30');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('1', '31');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('1', '32');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('1', '33');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('1', '34');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('1', '35');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('1', '36');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('1', '37');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('1', '38');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('1', '39');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('1', '40');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('2', '41');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('2', '42');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('2', '43');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('2', '44');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('2', '45');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('2', '46');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('2', '47');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('2', '48');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('2', '49');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('2', '50');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('2', '51');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('2', '52');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('2', '53');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('2', '54');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('2', '55');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('2', '56');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('2', '57');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('2', '58');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('2', '59');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('2', '60');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('2', '61');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('2', '62');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('2', '63');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('2', '64');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('2', '65');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('2', '66');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('2', '67');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('2', '68');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('2', '69');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('2', '70');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('2', '71');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('2', '72');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('2', '73');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('2', '74');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('2', '75');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('2', '76');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('2', '77');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('2', '78');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('2', '79');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('2', '80');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('2', '81');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('2', '82');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('3', '83');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('3', '84');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('3', '85');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('3', '86');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('3', '87');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('3', '88');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('3', '89');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('3', '90');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('3', '91');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('3', '92');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('3', '93');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('3', '94');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('3', '95');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('3', '96');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('3', '97');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('3', '98');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('3', '99');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('3', '100');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('3', '101');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('3', '102');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('3', '103');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('3', '104');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('3', '105');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('3', '106');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('3', '107');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('3', '108');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('3', '109');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('3', '110');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('3', '111');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('3', '112');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('3', '113');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('3', '114');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('3', '115');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('3', '116');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('3', '117');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('3', '118');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('3', '119');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('3', '120');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('3', '121');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('3', '122');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('3', '123');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('3', '124');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('4', '125');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('4', '126');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('4', '127');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('4', '128');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('4', '129');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('4', '130');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('4', '131');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('4', '132');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('4', '133');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('4', '134');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('4', '135');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('4', '136');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('4', '137');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('4', '138');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('4', '139');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('4', '140');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('4', '141');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('4', '142');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('4', '143');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('4', '144');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('4', '145');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('4', '146');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('4', '147');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('4', '148');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('4', '149');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('4', '150');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('4', '151');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('4', '152');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('4', '153');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('4', '154');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('4', '155');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('4', '156');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('4', '157');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('4', '158');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('4', '159');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('4', '160');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('4', '161');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('4', '162');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('4', '163');
INSERT INTO "iot_mqtt_category_authority" ("category_id", "authority_id") VALUES ('4', '164');

-- ----------------------------
-- Table data for iot_tsl_function
-- ----------------------------
INSERT INTO "iot_tsl_function" ("function_id", "create_time", "update_time", "create_by", "reversion", "update_by", "identifier", "argument_name", "argument_specs", "argument_type", "access_mode", "call_type", "description", "dimension", "event_type", "method", "is_required", "product_key", "product_id") VALUES ('74628d9f-455e-4ae6-b9b1-cca6de150401', '2025-05-02 17:36:14.683', '2025-05-02 17:36:14.683', 'system', 0, 'system', 'fan_boolean_property', '风扇布尔型属性', '{"identifier":"fan_boolean_property","name":"风扇布尔型属性","dataType":{"type":"bool","specs":{"0":"close","1":"open"}}}', 'BOOLEAN', 'READ_ONLY', NULL, NULL, 'PROPERTY', NULL, NULL, 'f', 'apktestadd', '8452271e-e42e-4a59-af80-3ea3c83247ea');
INSERT INTO "iot_tsl_function" ("function_id", "create_time", "update_time", "create_by", "reversion", "update_by", "identifier", "argument_name", "argument_specs", "argument_type", "access_mode", "call_type", "description", "dimension", "event_type", "method", "is_required", "product_key", "product_id") VALUES ('31094ce8-3aed-4ef5-9e5e-d056d6f9cf92', '2025-05-02 17:52:55.891', '2025-05-02 17:52:55.891', 'system', 0, 'system', 'fan_struct_property', '风扇结构型属性', '{"identifier":"fan_struct_property","name":"风扇结构型属性","dataType":{"type":"struct","specs":[{"identifier":"fan_struct_property_double_child","name":"风扇双精度型属性","dataType":{"type":"double","specs":{"min":"0.0","max":"100.0","unit":"mL","unitName":"毫升"}}},{"identifier":"fan_struct_property_float_child","name":"风扇结构型属性浮点子属性","dataType":{"type":"float","specs":{"min":"0.0","max":"100.0","unit":"mL","unitName":"毫升"}}},{"identifier":"fan_struct_property_int_child","name":"风扇结构型属性整数子属性","dataType":{"type":"int","specs":{"min":"0","max":"255","unit":"°","unitName":"度"}}},{"identifier":"fan_struct_property_text_child","name":"风扇结构型属性字符子属性","dataType":{"type":"text","specs":{"length":"200"}}},{"identifier":"fan_struct_property_date_child","name":"风扇结构型属性时间子属性","dataType":{"type":"date","specs":{}}},{"identifier":"fan_struct_property_boolean_child","name":"风扇结构型属性布尔子属性","dataType":{"type":"bool","specs":{"0":"close","1":"open"}}}]}}', 'STRUCT', 'READ_ONLY', NULL, NULL, 'PROPERTY', NULL, NULL, 'f', 'apktestadd', '8452271e-e42e-4a59-af80-3ea3c83247ea');
INSERT INTO "iot_tsl_function" ("function_id", "create_time", "update_time", "create_by", "reversion", "update_by", "identifier", "argument_name", "argument_specs", "argument_type", "access_mode", "call_type", "description", "dimension", "event_type", "method", "is_required", "product_key", "product_id") VALUES ('0050eef5-ec0d-464b-a6fd-3660b54c587c', '2025-05-02 18:00:34.934', '2025-05-02 18:00:34.934', 'system', 0, 'system', 'alarm', 'alarm', '{"identifier":"","name":"","dataType":{"type":"int","specs":{}}}', 'INTEGER', 'READ_WRITE', NULL, '警报', 'EVENT', 'INFO', NULL, 'f', 'apktestadd', '8452271e-e42e-4a59-af80-3ea3c83247ea');
INSERT INTO "iot_tsl_function" ("function_id", "create_time", "update_time", "create_by", "reversion", "update_by", "identifier", "argument_name", "argument_specs", "argument_type", "access_mode", "call_type", "description", "dimension", "event_type", "method", "is_required", "product_key", "product_id") VALUES ('f2efe631-8b29-4275-be21-11ad50d92e25', '2025-05-02 17:29:48.979', '2025-05-02 17:29:48.979', 'system', 0, 'system', 'fan_double_property', '风扇双精度型属性', '{"identifier":"fan_double_property","name":"风扇双精度型属性","dataType":{"type":"double","specs":{"min":"0.0","max":"100.0","unit":"mL","unitName":"毫升"}}}', 'DOUBLE', 'READ_ONLY', NULL, NULL, 'PROPERTY', NULL, NULL, 'f', 'apktestadd', '8452271e-e42e-4a59-af80-3ea3c83247ea');
INSERT INTO "iot_tsl_function" ("function_id", "create_time", "update_time", "create_by", "reversion", "update_by", "identifier", "argument_name", "argument_specs", "argument_type", "access_mode", "call_type", "description", "dimension", "event_type", "method", "is_required", "product_key", "product_id") VALUES ('fdece05b-39ad-49dc-9d00-ff3ee6bb8f04', '2025-05-02 17:30:33.086', '2025-05-02 17:30:33.086', 'system', 0, 'system', 'fan_int_property', '风扇整数型属性', '{"identifier":"fan_int_property","name":"风扇整数型属性","dataType":{"type":"int","specs":{"min":"0","max":"100","unit":"mL","unitName":"毫升"}}}', 'INTEGER', 'READ_WRITE', NULL, NULL, 'PROPERTY', NULL, NULL, 'f', 'apktestadd', '8452271e-e42e-4a59-af80-3ea3c83247ea');
INSERT INTO "iot_tsl_function" ("function_id", "create_time", "update_time", "create_by", "reversion", "update_by", "identifier", "argument_name", "argument_specs", "argument_type", "access_mode", "call_type", "description", "dimension", "event_type", "method", "is_required", "product_key", "product_id") VALUES ('779ace59-2e05-4c31-af72-821bccacaa10', '2025-05-02 17:34:57.42', '2025-05-02 17:34:57.42', 'system', 0, 'system', 'fan_date_property', '风扇时间型属性', '{"identifier":"fan_date_property","name":"风扇时间型属性","dataType":{"type":"date","specs":{}}}', 'DATE', 'READ_ONLY', NULL, NULL, 'PROPERTY', NULL, NULL, 'f', 'apktestadd', '8452271e-e42e-4a59-af80-3ea3c83247ea');
INSERT INTO "iot_tsl_function" ("function_id", "create_time", "update_time", "create_by", "reversion", "update_by", "identifier", "argument_name", "argument_specs", "argument_type", "access_mode", "call_type", "description", "dimension", "event_type", "method", "is_required", "product_key", "product_id") VALUES ('aa7ce843-b07d-4646-92db-28612d334a00', '2025-05-02 17:33:57.918', '2025-05-02 17:33:57.918', 'system', 0, 'system', 'fan_float_property', '风扇浮点型测试', '{"identifier":"fan_float_property","name":"风扇浮点型测试","dataType":{"type":"float","specs":{"min":"0.0","max":"100.0","unit":"mL","unitName":"毫升"}}}', 'FLOAT', 'READ_ONLY', NULL, NULL, 'PROPERTY', NULL, NULL, 'f', 'apktestadd', '8452271e-e42e-4a59-af80-3ea3c83247ea');
INSERT INTO "iot_tsl_function" ("function_id", "create_time", "update_time", "create_by", "reversion", "update_by", "identifier", "argument_name", "argument_specs", "argument_type", "access_mode", "call_type", "description", "dimension", "event_type", "method", "is_required", "product_key", "product_id") VALUES ('53087eef-9ac2-4ba7-9278-1b3b145a373b', '2025-05-02 17:34:31.732', '2025-05-02 17:34:31.732', 'system', 0, 'system', 'fan_text_property', '风扇字符型属性', '{"identifier":"fan_text_property","name":"风扇字符型属性","dataType":{"type":"text","specs":{"length":"64"}}}', 'TEXT', 'READ_ONLY', NULL, NULL, 'PROPERTY', NULL, NULL, 'f', 'apktestadd', '8452271e-e42e-4a59-af80-3ea3c83247ea');


-- ----------------------------
-- Table data for iot_tsl_argument
-- ----------------------------
INSERT INTO "iot_tsl_argument" ("argument_id", "create_time", "update_time", "create_by", "reversion", "update_by", "identifier", "argument_name", "argument_specs", "argument_type", "is_output") VALUES ('81cfdd74-1416-4a70-89f2-97a8b4caff40', '2025-05-02 18:00:34.933', '2025-05-02 18:00:34.933', 'system', 0, 'system', 'ErrorCode', '错误码', '{"identifier":"ErrorCode","name":"错误码","dataType":{"type":"text","specs":{"length":"255"}}}', 'TEXT', 't');

-- ----------------------------
-- Table data for iot_tsl_function_argument
-- ----------------------------
INSERT INTO "iot_tsl_function_argument" ("function_id", "argument_id") VALUES ('0050eef5-ec0d-464b-a6fd-3660b54c587c', '81cfdd74-1416-4a70-89f2-97a8b4caff40');
